///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package tb_design_axi_vip_0_0_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter tb_design_axi_vip_0_0_VIP_PROTOCOL           = 0;
      parameter tb_design_axi_vip_0_0_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter tb_design_axi_vip_0_0_VIP_INTERFACE_MODE     = 2;
      parameter tb_design_axi_vip_0_0_VIP_ADDR_WIDTH         = 32;
      parameter tb_design_axi_vip_0_0_VIP_DATA_WIDTH         = 32;
      parameter tb_design_axi_vip_0_0_VIP_ID_WIDTH           = 0;
      parameter tb_design_axi_vip_0_0_VIP_AWUSER_WIDTH       = 0;
      parameter tb_design_axi_vip_0_0_VIP_ARUSER_WIDTH       = 0;
      parameter tb_design_axi_vip_0_0_VIP_RUSER_WIDTH        = 0;
      parameter tb_design_axi_vip_0_0_VIP_WUSER_WIDTH        = 0;
      parameter tb_design_axi_vip_0_0_VIP_BUSER_WIDTH        = 0;
      parameter tb_design_axi_vip_0_0_VIP_SUPPORTS_NARROW    = 0;
      parameter tb_design_axi_vip_0_0_VIP_HAS_BURST          = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_LOCK           = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_CACHE          = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_REGION         = 0;
      parameter tb_design_axi_vip_0_0_VIP_HAS_QOS            = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_PROT           = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_WSTRB          = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_BRESP          = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_RRESP          = 1;
      parameter tb_design_axi_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter tb_design_axi_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi_slv_agent #(tb_design_axi_vip_0_0_VIP_PROTOCOL, 
                        tb_design_axi_vip_0_0_VIP_ADDR_WIDTH,
                        tb_design_axi_vip_0_0_VIP_DATA_WIDTH,
                        tb_design_axi_vip_0_0_VIP_DATA_WIDTH,
                        tb_design_axi_vip_0_0_VIP_ID_WIDTH,
                        tb_design_axi_vip_0_0_VIP_ID_WIDTH,
                        tb_design_axi_vip_0_0_VIP_AWUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_WUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_BUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_ARUSER_WIDTH,
                        tb_design_axi_vip_0_0_VIP_RUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_SUPPORTS_NARROW, 
                        tb_design_axi_vip_0_0_VIP_HAS_BURST,
                        tb_design_axi_vip_0_0_VIP_HAS_LOCK,
                        tb_design_axi_vip_0_0_VIP_HAS_CACHE,
                        tb_design_axi_vip_0_0_VIP_HAS_REGION,
                        tb_design_axi_vip_0_0_VIP_HAS_PROT,
                        tb_design_axi_vip_0_0_VIP_HAS_QOS,
                        tb_design_axi_vip_0_0_VIP_HAS_WSTRB,
                        tb_design_axi_vip_0_0_VIP_HAS_BRESP,
                        tb_design_axi_vip_0_0_VIP_HAS_RRESP,
                        tb_design_axi_vip_0_0_VIP_HAS_ARESETN) tb_design_axi_vip_0_0_slv_t;

typedef axi_slv_mem_agent #(tb_design_axi_vip_0_0_VIP_PROTOCOL, 
                        tb_design_axi_vip_0_0_VIP_ADDR_WIDTH,
                        tb_design_axi_vip_0_0_VIP_DATA_WIDTH,
                        tb_design_axi_vip_0_0_VIP_DATA_WIDTH,
                        tb_design_axi_vip_0_0_VIP_ID_WIDTH,
                        tb_design_axi_vip_0_0_VIP_ID_WIDTH,
                        tb_design_axi_vip_0_0_VIP_AWUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_WUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_BUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_ARUSER_WIDTH,
                        tb_design_axi_vip_0_0_VIP_RUSER_WIDTH, 
                        tb_design_axi_vip_0_0_VIP_SUPPORTS_NARROW, 
                        tb_design_axi_vip_0_0_VIP_HAS_BURST,
                        tb_design_axi_vip_0_0_VIP_HAS_LOCK,
                        tb_design_axi_vip_0_0_VIP_HAS_CACHE,
                        tb_design_axi_vip_0_0_VIP_HAS_REGION,
                        tb_design_axi_vip_0_0_VIP_HAS_PROT,
                        tb_design_axi_vip_0_0_VIP_HAS_QOS,
                        tb_design_axi_vip_0_0_VIP_HAS_WSTRB,
                        tb_design_axi_vip_0_0_VIP_HAS_BRESP,
                        tb_design_axi_vip_0_0_VIP_HAS_RRESP,
                        tb_design_axi_vip_0_0_VIP_HAS_ARESETN) tb_design_axi_vip_0_0_slv_mem_t;
                        
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      tb_design_axi_vip_0_0_slv_t  tb_design_axi_vip_0_0_slv;
//      initial begin : START_tb_design_axi_vip_0_0_SLAVE
//        tb_design_axi_vip_0_0_slv = new("tb_design_axi_vip_0_0_slv", `tb_design_axi_vip_0_0_PATH_TO_INTERFACE);
//        tb_design_axi_vip_0_0_slv.start_slave();
//      end

endpackage : tb_design_axi_vip_0_0_pkg
