set_property PACKAGE_PIN A20 [get_ports reset_rtl_0]


### SODIMM_HT3 JX1 JX2 JX3
### EPS_VU13P  JX7 JX6 JX5

#create_clock -period 3.333 -name ddr4_ref_clk [get_ports diff_clock_rtl_0_clk_p]

set_property -dict {PACKAGE_PIN AG31 IOSTANDARD LVCMOS12} [get_ports c0_ddr4_32G_reset_n]
set_property -dict {PACKAGE_PIN AE31 IOSTANDARD DIFF_SSTL12} [get_ports diff_clock_rtl_0_clk_p]
set_property -dict {PACKAGE_PIN AE32 IOSTANDARD DIFF_SSTL12} [get_ports diff_clock_rtl_0_clk_n]
set_property -dict {PACKAGE_PIN AH32 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports c0_ddr4_32G_act_n]

set_property -dict {PACKAGE_PIN W30 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[0]}]
set_property -dict {PACKAGE_PIN Y30 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[1]}]
set_property -dict {PACKAGE_PIN W31 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[2]}]
set_property -dict {PACKAGE_PIN Y31 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[3]}]
set_property -dict {PACKAGE_PIN Y32 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[4]}]
set_property -dict {PACKAGE_PIN Y33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[5]}]
set_property -dict {PACKAGE_PIN W33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[6]}]
set_property -dict {PACKAGE_PIN W34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[7]}]
set_property -dict {PACKAGE_PIN AB32 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[8]}]
set_property -dict {PACKAGE_PIN AD33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[9]}]
set_property -dict {PACKAGE_PIN AE33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[10]}]
set_property -dict {PACKAGE_PIN AE30 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[11]}]
set_property -dict {PACKAGE_PIN AF30 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[12]}]
set_property -dict {PACKAGE_PIN AC31 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[13]}]
set_property -dict {PACKAGE_PIN AD31 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[14]}]
set_property -dict {PACKAGE_PIN AC32 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[15]}]
set_property -dict {PACKAGE_PIN AC33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_adr[16]}]

set_property -dict {PACKAGE_PIN AC34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_ba[0]}]
set_property -dict {PACKAGE_PIN AD34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_ba[1]}]

set_property -dict {PACKAGE_PIN AG32 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_bg[0]}]
set_property -dict {PACKAGE_PIN AH34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_bg[1]}]

set_property -dict {PACKAGE_PIN AA32 IOSTANDARD DIFF_SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_ck_t[0]}]
set_property -dict {PACKAGE_PIN AA33 IOSTANDARD DIFF_SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_ck_c[0]}]
set_property -dict {PACKAGE_PIN AA34 IOSTANDARD DIFF_SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_ck_t[1]}]
set_property -dict {PACKAGE_PIN AB34 IOSTANDARD DIFF_SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_ck_c[1]}]

set_property -dict {PACKAGE_PIN AJ33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_cke[0]}]
set_property -dict {PACKAGE_PIN AF34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_cke[1]}]

set_property -dict {PACKAGE_PIN AJ34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST} [get_ports {c0_ddr4_32G_cs_n[0]}]
set_property -dict {PACKAGE_PIN AH33 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST} [get_ports {c0_ddr4_32G_cs_n[1]}]

set_property -dict {PACKAGE_PIN AJ27 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[0]}]
set_property -dict {PACKAGE_PIN AT33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[1]}]
set_property -dict {PACKAGE_PIN BA34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[2]}]
set_property -dict {PACKAGE_PIN BC34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[3]}]
set_property -dict {PACKAGE_PIN BF39 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[4]}]
set_property -dict {PACKAGE_PIN AP31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[5]}]
set_property -dict {PACKAGE_PIN AW29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[6]}]
set_property -dict {PACKAGE_PIN BC31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dm_n[7]}]

set_property -dict {PACKAGE_PIN AJ28 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[0]}]
set_property -dict {PACKAGE_PIN AK28 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[1]}]
set_property -dict {PACKAGE_PIN AJ29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[2]}]
set_property -dict {PACKAGE_PIN AJ30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[3]}]
set_property -dict {PACKAGE_PIN AG29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[4]}]
set_property -dict {PACKAGE_PIN AG30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[5]}]
set_property -dict {PACKAGE_PIN AJ31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[6]}]
set_property -dict {PACKAGE_PIN AK31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[7]}]
set_property -dict {PACKAGE_PIN AP33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[8]}]
set_property -dict {PACKAGE_PIN AR33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[9]}]
set_property -dict {PACKAGE_PIN AN34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[10]}]
set_property -dict {PACKAGE_PIN AP34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[11]}]
set_property -dict {PACKAGE_PIN AL32 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[12]}]
set_property -dict {PACKAGE_PIN AM32 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[13]}]
set_property -dict {PACKAGE_PIN AL34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[14]}]
set_property -dict {PACKAGE_PIN AM34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[15]}]
set_property -dict {PACKAGE_PIN AY35 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[16]}]
set_property -dict {PACKAGE_PIN AY36 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[17]}]
set_property -dict {PACKAGE_PIN AY33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[18]}]
set_property -dict {PACKAGE_PIN BA33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[19]}]
set_property -dict {PACKAGE_PIN AV34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[20]}]
set_property -dict {PACKAGE_PIN AW34 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[21]}]
set_property -dict {PACKAGE_PIN AV33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[22]}]
set_property -dict {PACKAGE_PIN AW33 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[23]}]
set_property -dict {PACKAGE_PIN BD35 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[24]}]
set_property -dict {PACKAGE_PIN BE35 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[25]}]
set_property -dict {PACKAGE_PIN BD36 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[26]}]
set_property -dict {PACKAGE_PIN BE36 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[27]}]
set_property -dict {PACKAGE_PIN BB36 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[28]}]
set_property -dict {PACKAGE_PIN BC36 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[29]}]
set_property -dict {PACKAGE_PIN BA35 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[30]}]
set_property -dict {PACKAGE_PIN BB35 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[31]}]
set_property -dict {PACKAGE_PIN BE38 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[32]}]
set_property -dict {PACKAGE_PIN BF38 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[33]}]
set_property -dict {PACKAGE_PIN BE37 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[34]}]
set_property -dict {PACKAGE_PIN BF37 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[35]}]
set_property -dict {PACKAGE_PIN BC39 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[36]}]
set_property -dict {PACKAGE_PIN BD39 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[37]}]
set_property -dict {PACKAGE_PIN BB38 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[38]}]
set_property -dict {PACKAGE_PIN BC38 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[39]}]
set_property -dict {PACKAGE_PIN AP30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[40]}]
set_property -dict {PACKAGE_PIN AR30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[41]}]
set_property -dict {PACKAGE_PIN AN29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[42]}]
set_property -dict {PACKAGE_PIN AP29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[43]}]
set_property -dict {PACKAGE_PIN AM31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[44]}]
set_property -dict {PACKAGE_PIN AN31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[45]}]
set_property -dict {PACKAGE_PIN AL29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[46]}]
set_property -dict {PACKAGE_PIN AL30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[47]}]
set_property -dict {PACKAGE_PIN AV31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[48]}]
set_property -dict {PACKAGE_PIN AW31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[49]}]
set_property -dict {PACKAGE_PIN AU32 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[50]}]
set_property -dict {PACKAGE_PIN AV32 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[51]}]
set_property -dict {PACKAGE_PIN AU30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[52]}]
set_property -dict {PACKAGE_PIN AU31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[53]}]
set_property -dict {PACKAGE_PIN AT29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[54]}]
set_property -dict {PACKAGE_PIN AT30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[55]}]
set_property -dict {PACKAGE_PIN BB30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[56]}]
set_property -dict {PACKAGE_PIN BB31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[57]}]
set_property -dict {PACKAGE_PIN BA29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[58]}]
set_property -dict {PACKAGE_PIN BB29 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[59]}]
set_property -dict {PACKAGE_PIN AY30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[60]}]
set_property -dict {PACKAGE_PIN BA30 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[61]}]
set_property -dict {PACKAGE_PIN AY31 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[62]}]
set_property -dict {PACKAGE_PIN AY32 IOSTANDARD POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dq[63]}]

set_property -dict {PACKAGE_PIN AH28 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[0]}]
set_property -dict {PACKAGE_PIN AH29 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[0]}]
set_property -dict {PACKAGE_PIN AN32 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[1]}]
set_property -dict {PACKAGE_PIN AN33 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[1]}]
set_property -dict {PACKAGE_PIN AW35 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[2]}]
set_property -dict {PACKAGE_PIN AW36 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[2]}]
set_property -dict {PACKAGE_PIN BB37 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[3]}]
set_property -dict {PACKAGE_PIN BC37 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[3]}]
set_property -dict {PACKAGE_PIN BD40 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[4]}]
set_property -dict {PACKAGE_PIN BE40 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[4]}]
set_property -dict {PACKAGE_PIN AM29 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[5]}]
set_property -dict {PACKAGE_PIN AM30 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[5]}]
set_property -dict {PACKAGE_PIN AU29 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[6]}]
set_property -dict {PACKAGE_PIN AV29 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[6]}]
set_property -dict {PACKAGE_PIN BA32 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_t[7]}]
set_property -dict {PACKAGE_PIN BB32 IOSTANDARD DIFF_POD12_DCI OUTPUT_IMPEDANCE RDRV_40_40 IBUF_LOW_PWR 0} [get_ports {c0_ddr4_32G_dqs_c[7]}]

set_property -dict {PACKAGE_PIN AG34 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_odt[0]}]
set_property -dict {PACKAGE_PIN AH31 IOSTANDARD SSTL12_DCI OUTPUT_IMPEDANCE RDRV_40_40} [get_ports {c0_ddr4_32G_odt[1]}]

# Set the electrical voltage standard for your reset button
set_property IOSTANDARD LVCMOS18 [get_ports reset_rtl_0]

# Set the 1.2V differential electrical standard for your DDR reference clock


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/ddr4_0/inst/u_ddr4_infrastructure/u_bufg_divClk_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_AWBURST[0]} {design_1_i/npu_axi_full_0_m_axi_AWBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_ARADDR[0]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[1]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[2]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[3]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[4]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[5]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[6]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[7]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[8]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[9]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[10]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[11]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[12]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[13]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[14]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[15]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[16]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[17]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[18]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[19]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[20]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[21]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[22]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[23]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[24]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[25]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[26]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[27]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[28]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[29]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[30]} {design_1_i/npu_axi_full_0_m_axi_ARADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_WSTRB[0]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[1]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[2]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[3]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[4]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[5]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[6]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[7]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[8]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[9]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[10]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[11]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[12]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[13]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[14]} {design_1_i/npu_axi_full_0_m_axi_WSTRB[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 128 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_RDATA[0]} {design_1_i/npu_axi_full_0_m_axi_RDATA[1]} {design_1_i/npu_axi_full_0_m_axi_RDATA[2]} {design_1_i/npu_axi_full_0_m_axi_RDATA[3]} {design_1_i/npu_axi_full_0_m_axi_RDATA[4]} {design_1_i/npu_axi_full_0_m_axi_RDATA[5]} {design_1_i/npu_axi_full_0_m_axi_RDATA[6]} {design_1_i/npu_axi_full_0_m_axi_RDATA[7]} {design_1_i/npu_axi_full_0_m_axi_RDATA[8]} {design_1_i/npu_axi_full_0_m_axi_RDATA[9]} {design_1_i/npu_axi_full_0_m_axi_RDATA[10]} {design_1_i/npu_axi_full_0_m_axi_RDATA[11]} {design_1_i/npu_axi_full_0_m_axi_RDATA[12]} {design_1_i/npu_axi_full_0_m_axi_RDATA[13]} {design_1_i/npu_axi_full_0_m_axi_RDATA[14]} {design_1_i/npu_axi_full_0_m_axi_RDATA[15]} {design_1_i/npu_axi_full_0_m_axi_RDATA[16]} {design_1_i/npu_axi_full_0_m_axi_RDATA[17]} {design_1_i/npu_axi_full_0_m_axi_RDATA[18]} {design_1_i/npu_axi_full_0_m_axi_RDATA[19]} {design_1_i/npu_axi_full_0_m_axi_RDATA[20]} {design_1_i/npu_axi_full_0_m_axi_RDATA[21]} {design_1_i/npu_axi_full_0_m_axi_RDATA[22]} {design_1_i/npu_axi_full_0_m_axi_RDATA[23]} {design_1_i/npu_axi_full_0_m_axi_RDATA[24]} {design_1_i/npu_axi_full_0_m_axi_RDATA[25]} {design_1_i/npu_axi_full_0_m_axi_RDATA[26]} {design_1_i/npu_axi_full_0_m_axi_RDATA[27]} {design_1_i/npu_axi_full_0_m_axi_RDATA[28]} {design_1_i/npu_axi_full_0_m_axi_RDATA[29]} {design_1_i/npu_axi_full_0_m_axi_RDATA[30]} {design_1_i/npu_axi_full_0_m_axi_RDATA[31]} {design_1_i/npu_axi_full_0_m_axi_RDATA[32]} {design_1_i/npu_axi_full_0_m_axi_RDATA[33]} {design_1_i/npu_axi_full_0_m_axi_RDATA[34]} {design_1_i/npu_axi_full_0_m_axi_RDATA[35]} {design_1_i/npu_axi_full_0_m_axi_RDATA[36]} {design_1_i/npu_axi_full_0_m_axi_RDATA[37]} {design_1_i/npu_axi_full_0_m_axi_RDATA[38]} {design_1_i/npu_axi_full_0_m_axi_RDATA[39]} {design_1_i/npu_axi_full_0_m_axi_RDATA[40]} {design_1_i/npu_axi_full_0_m_axi_RDATA[41]} {design_1_i/npu_axi_full_0_m_axi_RDATA[42]} {design_1_i/npu_axi_full_0_m_axi_RDATA[43]} {design_1_i/npu_axi_full_0_m_axi_RDATA[44]} {design_1_i/npu_axi_full_0_m_axi_RDATA[45]} {design_1_i/npu_axi_full_0_m_axi_RDATA[46]} {design_1_i/npu_axi_full_0_m_axi_RDATA[47]} {design_1_i/npu_axi_full_0_m_axi_RDATA[48]} {design_1_i/npu_axi_full_0_m_axi_RDATA[49]} {design_1_i/npu_axi_full_0_m_axi_RDATA[50]} {design_1_i/npu_axi_full_0_m_axi_RDATA[51]} {design_1_i/npu_axi_full_0_m_axi_RDATA[52]} {design_1_i/npu_axi_full_0_m_axi_RDATA[53]} {design_1_i/npu_axi_full_0_m_axi_RDATA[54]} {design_1_i/npu_axi_full_0_m_axi_RDATA[55]} {design_1_i/npu_axi_full_0_m_axi_RDATA[56]} {design_1_i/npu_axi_full_0_m_axi_RDATA[57]} {design_1_i/npu_axi_full_0_m_axi_RDATA[58]} {design_1_i/npu_axi_full_0_m_axi_RDATA[59]} {design_1_i/npu_axi_full_0_m_axi_RDATA[60]} {design_1_i/npu_axi_full_0_m_axi_RDATA[61]} {design_1_i/npu_axi_full_0_m_axi_RDATA[62]} {design_1_i/npu_axi_full_0_m_axi_RDATA[63]} {design_1_i/npu_axi_full_0_m_axi_RDATA[64]} {design_1_i/npu_axi_full_0_m_axi_RDATA[65]} {design_1_i/npu_axi_full_0_m_axi_RDATA[66]} {design_1_i/npu_axi_full_0_m_axi_RDATA[67]} {design_1_i/npu_axi_full_0_m_axi_RDATA[68]} {design_1_i/npu_axi_full_0_m_axi_RDATA[69]} {design_1_i/npu_axi_full_0_m_axi_RDATA[70]} {design_1_i/npu_axi_full_0_m_axi_RDATA[71]} {design_1_i/npu_axi_full_0_m_axi_RDATA[72]} {design_1_i/npu_axi_full_0_m_axi_RDATA[73]} {design_1_i/npu_axi_full_0_m_axi_RDATA[74]} {design_1_i/npu_axi_full_0_m_axi_RDATA[75]} {design_1_i/npu_axi_full_0_m_axi_RDATA[76]} {design_1_i/npu_axi_full_0_m_axi_RDATA[77]} {design_1_i/npu_axi_full_0_m_axi_RDATA[78]} {design_1_i/npu_axi_full_0_m_axi_RDATA[79]} {design_1_i/npu_axi_full_0_m_axi_RDATA[80]} {design_1_i/npu_axi_full_0_m_axi_RDATA[81]} {design_1_i/npu_axi_full_0_m_axi_RDATA[82]} {design_1_i/npu_axi_full_0_m_axi_RDATA[83]} {design_1_i/npu_axi_full_0_m_axi_RDATA[84]} {design_1_i/npu_axi_full_0_m_axi_RDATA[85]} {design_1_i/npu_axi_full_0_m_axi_RDATA[86]} {design_1_i/npu_axi_full_0_m_axi_RDATA[87]} {design_1_i/npu_axi_full_0_m_axi_RDATA[88]} {design_1_i/npu_axi_full_0_m_axi_RDATA[89]} {design_1_i/npu_axi_full_0_m_axi_RDATA[90]} {design_1_i/npu_axi_full_0_m_axi_RDATA[91]} {design_1_i/npu_axi_full_0_m_axi_RDATA[92]} {design_1_i/npu_axi_full_0_m_axi_RDATA[93]} {design_1_i/npu_axi_full_0_m_axi_RDATA[94]} {design_1_i/npu_axi_full_0_m_axi_RDATA[95]} {design_1_i/npu_axi_full_0_m_axi_RDATA[96]} {design_1_i/npu_axi_full_0_m_axi_RDATA[97]} {design_1_i/npu_axi_full_0_m_axi_RDATA[98]} {design_1_i/npu_axi_full_0_m_axi_RDATA[99]} {design_1_i/npu_axi_full_0_m_axi_RDATA[100]} {design_1_i/npu_axi_full_0_m_axi_RDATA[101]} {design_1_i/npu_axi_full_0_m_axi_RDATA[102]} {design_1_i/npu_axi_full_0_m_axi_RDATA[103]} {design_1_i/npu_axi_full_0_m_axi_RDATA[104]} {design_1_i/npu_axi_full_0_m_axi_RDATA[105]} {design_1_i/npu_axi_full_0_m_axi_RDATA[106]} {design_1_i/npu_axi_full_0_m_axi_RDATA[107]} {design_1_i/npu_axi_full_0_m_axi_RDATA[108]} {design_1_i/npu_axi_full_0_m_axi_RDATA[109]} {design_1_i/npu_axi_full_0_m_axi_RDATA[110]} {design_1_i/npu_axi_full_0_m_axi_RDATA[111]} {design_1_i/npu_axi_full_0_m_axi_RDATA[112]} {design_1_i/npu_axi_full_0_m_axi_RDATA[113]} {design_1_i/npu_axi_full_0_m_axi_RDATA[114]} {design_1_i/npu_axi_full_0_m_axi_RDATA[115]} {design_1_i/npu_axi_full_0_m_axi_RDATA[116]} {design_1_i/npu_axi_full_0_m_axi_RDATA[117]} {design_1_i/npu_axi_full_0_m_axi_RDATA[118]} {design_1_i/npu_axi_full_0_m_axi_RDATA[119]} {design_1_i/npu_axi_full_0_m_axi_RDATA[120]} {design_1_i/npu_axi_full_0_m_axi_RDATA[121]} {design_1_i/npu_axi_full_0_m_axi_RDATA[122]} {design_1_i/npu_axi_full_0_m_axi_RDATA[123]} {design_1_i/npu_axi_full_0_m_axi_RDATA[124]} {design_1_i/npu_axi_full_0_m_axi_RDATA[125]} {design_1_i/npu_axi_full_0_m_axi_RDATA[126]} {design_1_i/npu_axi_full_0_m_axi_RDATA[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_ARLEN[0]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[1]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[2]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[3]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[4]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[5]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[6]} {design_1_i/npu_axi_full_0_m_axi_ARLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 3 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_ARSIZE[0]} {design_1_i/npu_axi_full_0_m_axi_ARSIZE[1]} {design_1_i/npu_axi_full_0_m_axi_ARSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_BRESP[0]} {design_1_i/npu_axi_full_0_m_axi_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/state_o[0]} {design_1_i/state_o[1]} {design_1_i/state_o[2]} {design_1_i/state_o[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 3 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_AWSIZE[0]} {design_1_i/npu_axi_full_0_m_axi_AWSIZE[1]} {design_1_i/npu_axi_full_0_m_axi_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 128 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_WDATA[0]} {design_1_i/npu_axi_full_0_m_axi_WDATA[1]} {design_1_i/npu_axi_full_0_m_axi_WDATA[2]} {design_1_i/npu_axi_full_0_m_axi_WDATA[3]} {design_1_i/npu_axi_full_0_m_axi_WDATA[4]} {design_1_i/npu_axi_full_0_m_axi_WDATA[5]} {design_1_i/npu_axi_full_0_m_axi_WDATA[6]} {design_1_i/npu_axi_full_0_m_axi_WDATA[7]} {design_1_i/npu_axi_full_0_m_axi_WDATA[8]} {design_1_i/npu_axi_full_0_m_axi_WDATA[9]} {design_1_i/npu_axi_full_0_m_axi_WDATA[10]} {design_1_i/npu_axi_full_0_m_axi_WDATA[11]} {design_1_i/npu_axi_full_0_m_axi_WDATA[12]} {design_1_i/npu_axi_full_0_m_axi_WDATA[13]} {design_1_i/npu_axi_full_0_m_axi_WDATA[14]} {design_1_i/npu_axi_full_0_m_axi_WDATA[15]} {design_1_i/npu_axi_full_0_m_axi_WDATA[16]} {design_1_i/npu_axi_full_0_m_axi_WDATA[17]} {design_1_i/npu_axi_full_0_m_axi_WDATA[18]} {design_1_i/npu_axi_full_0_m_axi_WDATA[19]} {design_1_i/npu_axi_full_0_m_axi_WDATA[20]} {design_1_i/npu_axi_full_0_m_axi_WDATA[21]} {design_1_i/npu_axi_full_0_m_axi_WDATA[22]} {design_1_i/npu_axi_full_0_m_axi_WDATA[23]} {design_1_i/npu_axi_full_0_m_axi_WDATA[24]} {design_1_i/npu_axi_full_0_m_axi_WDATA[25]} {design_1_i/npu_axi_full_0_m_axi_WDATA[26]} {design_1_i/npu_axi_full_0_m_axi_WDATA[27]} {design_1_i/npu_axi_full_0_m_axi_WDATA[28]} {design_1_i/npu_axi_full_0_m_axi_WDATA[29]} {design_1_i/npu_axi_full_0_m_axi_WDATA[30]} {design_1_i/npu_axi_full_0_m_axi_WDATA[31]} {design_1_i/npu_axi_full_0_m_axi_WDATA[32]} {design_1_i/npu_axi_full_0_m_axi_WDATA[33]} {design_1_i/npu_axi_full_0_m_axi_WDATA[34]} {design_1_i/npu_axi_full_0_m_axi_WDATA[35]} {design_1_i/npu_axi_full_0_m_axi_WDATA[36]} {design_1_i/npu_axi_full_0_m_axi_WDATA[37]} {design_1_i/npu_axi_full_0_m_axi_WDATA[38]} {design_1_i/npu_axi_full_0_m_axi_WDATA[39]} {design_1_i/npu_axi_full_0_m_axi_WDATA[40]} {design_1_i/npu_axi_full_0_m_axi_WDATA[41]} {design_1_i/npu_axi_full_0_m_axi_WDATA[42]} {design_1_i/npu_axi_full_0_m_axi_WDATA[43]} {design_1_i/npu_axi_full_0_m_axi_WDATA[44]} {design_1_i/npu_axi_full_0_m_axi_WDATA[45]} {design_1_i/npu_axi_full_0_m_axi_WDATA[46]} {design_1_i/npu_axi_full_0_m_axi_WDATA[47]} {design_1_i/npu_axi_full_0_m_axi_WDATA[48]} {design_1_i/npu_axi_full_0_m_axi_WDATA[49]} {design_1_i/npu_axi_full_0_m_axi_WDATA[50]} {design_1_i/npu_axi_full_0_m_axi_WDATA[51]} {design_1_i/npu_axi_full_0_m_axi_WDATA[52]} {design_1_i/npu_axi_full_0_m_axi_WDATA[53]} {design_1_i/npu_axi_full_0_m_axi_WDATA[54]} {design_1_i/npu_axi_full_0_m_axi_WDATA[55]} {design_1_i/npu_axi_full_0_m_axi_WDATA[56]} {design_1_i/npu_axi_full_0_m_axi_WDATA[57]} {design_1_i/npu_axi_full_0_m_axi_WDATA[58]} {design_1_i/npu_axi_full_0_m_axi_WDATA[59]} {design_1_i/npu_axi_full_0_m_axi_WDATA[60]} {design_1_i/npu_axi_full_0_m_axi_WDATA[61]} {design_1_i/npu_axi_full_0_m_axi_WDATA[62]} {design_1_i/npu_axi_full_0_m_axi_WDATA[63]} {design_1_i/npu_axi_full_0_m_axi_WDATA[64]} {design_1_i/npu_axi_full_0_m_axi_WDATA[65]} {design_1_i/npu_axi_full_0_m_axi_WDATA[66]} {design_1_i/npu_axi_full_0_m_axi_WDATA[67]} {design_1_i/npu_axi_full_0_m_axi_WDATA[68]} {design_1_i/npu_axi_full_0_m_axi_WDATA[69]} {design_1_i/npu_axi_full_0_m_axi_WDATA[70]} {design_1_i/npu_axi_full_0_m_axi_WDATA[71]} {design_1_i/npu_axi_full_0_m_axi_WDATA[72]} {design_1_i/npu_axi_full_0_m_axi_WDATA[73]} {design_1_i/npu_axi_full_0_m_axi_WDATA[74]} {design_1_i/npu_axi_full_0_m_axi_WDATA[75]} {design_1_i/npu_axi_full_0_m_axi_WDATA[76]} {design_1_i/npu_axi_full_0_m_axi_WDATA[77]} {design_1_i/npu_axi_full_0_m_axi_WDATA[78]} {design_1_i/npu_axi_full_0_m_axi_WDATA[79]} {design_1_i/npu_axi_full_0_m_axi_WDATA[80]} {design_1_i/npu_axi_full_0_m_axi_WDATA[81]} {design_1_i/npu_axi_full_0_m_axi_WDATA[82]} {design_1_i/npu_axi_full_0_m_axi_WDATA[83]} {design_1_i/npu_axi_full_0_m_axi_WDATA[84]} {design_1_i/npu_axi_full_0_m_axi_WDATA[85]} {design_1_i/npu_axi_full_0_m_axi_WDATA[86]} {design_1_i/npu_axi_full_0_m_axi_WDATA[87]} {design_1_i/npu_axi_full_0_m_axi_WDATA[88]} {design_1_i/npu_axi_full_0_m_axi_WDATA[89]} {design_1_i/npu_axi_full_0_m_axi_WDATA[90]} {design_1_i/npu_axi_full_0_m_axi_WDATA[91]} {design_1_i/npu_axi_full_0_m_axi_WDATA[92]} {design_1_i/npu_axi_full_0_m_axi_WDATA[93]} {design_1_i/npu_axi_full_0_m_axi_WDATA[94]} {design_1_i/npu_axi_full_0_m_axi_WDATA[95]} {design_1_i/npu_axi_full_0_m_axi_WDATA[96]} {design_1_i/npu_axi_full_0_m_axi_WDATA[97]} {design_1_i/npu_axi_full_0_m_axi_WDATA[98]} {design_1_i/npu_axi_full_0_m_axi_WDATA[99]} {design_1_i/npu_axi_full_0_m_axi_WDATA[100]} {design_1_i/npu_axi_full_0_m_axi_WDATA[101]} {design_1_i/npu_axi_full_0_m_axi_WDATA[102]} {design_1_i/npu_axi_full_0_m_axi_WDATA[103]} {design_1_i/npu_axi_full_0_m_axi_WDATA[104]} {design_1_i/npu_axi_full_0_m_axi_WDATA[105]} {design_1_i/npu_axi_full_0_m_axi_WDATA[106]} {design_1_i/npu_axi_full_0_m_axi_WDATA[107]} {design_1_i/npu_axi_full_0_m_axi_WDATA[108]} {design_1_i/npu_axi_full_0_m_axi_WDATA[109]} {design_1_i/npu_axi_full_0_m_axi_WDATA[110]} {design_1_i/npu_axi_full_0_m_axi_WDATA[111]} {design_1_i/npu_axi_full_0_m_axi_WDATA[112]} {design_1_i/npu_axi_full_0_m_axi_WDATA[113]} {design_1_i/npu_axi_full_0_m_axi_WDATA[114]} {design_1_i/npu_axi_full_0_m_axi_WDATA[115]} {design_1_i/npu_axi_full_0_m_axi_WDATA[116]} {design_1_i/npu_axi_full_0_m_axi_WDATA[117]} {design_1_i/npu_axi_full_0_m_axi_WDATA[118]} {design_1_i/npu_axi_full_0_m_axi_WDATA[119]} {design_1_i/npu_axi_full_0_m_axi_WDATA[120]} {design_1_i/npu_axi_full_0_m_axi_WDATA[121]} {design_1_i/npu_axi_full_0_m_axi_WDATA[122]} {design_1_i/npu_axi_full_0_m_axi_WDATA[123]} {design_1_i/npu_axi_full_0_m_axi_WDATA[124]} {design_1_i/npu_axi_full_0_m_axi_WDATA[125]} {design_1_i/npu_axi_full_0_m_axi_WDATA[126]} {design_1_i/npu_axi_full_0_m_axi_WDATA[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_ARBURST[0]} {design_1_i/npu_axi_full_0_m_axi_ARBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_AWLEN[0]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[1]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[2]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[3]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[4]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[5]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[6]} {design_1_i/npu_axi_full_0_m_axi_AWLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 2 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_RRESP[0]} {design_1_i/npu_axi_full_0_m_axi_RRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/npu_axi_full_0_m_axi_AWADDR[0]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[1]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[2]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[3]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[4]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[5]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[6]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[7]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[8]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[9]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[10]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[11]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[12]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[13]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[14]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[15]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[16]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[17]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[18]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[19]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[20]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[21]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[22]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[23]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[24]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[25]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[26]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[27]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[28]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[29]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[30]} {design_1_i/npu_axi_full_0_m_axi_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/npu_axi_full_0_m_axi_ARREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/npu_axi_full_0_m_axi_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/npu_axi_full_0_m_axi_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/npu_axi_full_0_m_axi_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/npu_axi_full_0_m_axi_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/npu_axi_full_0_m_axi_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/npu_axi_full_0_m_axi_RLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/npu_axi_full_0_m_axi_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/npu_axi_full_0_m_axi_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/npu_axi_full_0_m_axi_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/npu_axi_full_0_m_axi_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/npu_axi_full_0_m_axi_WVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/start_pulse_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/npu_axi_full_0_busy_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/npu_axi_full_0_done_o]]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
