#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Script generated by Vivado on Tue Jul 14 14:53:35 CST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-rerun]
#                design_1.sh [-reset_run]
#                design_1.sh [-clean]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************
export SIM_VER_VCS=
export GCC_VER_VCS=

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm microblaze_v11_0_16 xil_defaultlib proc_sys_reset_v5_0_17 lmb_v10_v3_0_16 lmb_bram_if_cntlr_v4_0_27 blk_mem_gen_v8_4_12 iomodule_v3_1_13 jtag_axi smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_36 axi_vip_v1_1_22 util_vector_logic_v2_0_5)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2025.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/opt/Xilinx/2025.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/opt/Xilinx/2025.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/opt/Xilinx/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/opt/Xilinx/2025.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vhdlan -work microblaze_v11_0_16 $vhdlan_opts \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/c957/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_0/sim/bd_be6b_microblaze_I_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_17 $vhdlan_opts \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_1/sim/bd_be6b_rst_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_v10_v3_0_16 $vhdlan_opts \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/dac4/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_2/sim/bd_be6b_ilmb_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_3/sim/bd_be6b_dlmb_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_bram_if_cntlr_v4_0_27 $vhdlan_opts \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/7cd0/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_4/sim/bd_be6b_dlmb_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_5/sim/bd_be6b_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_12 $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/42f3/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_6/sim/bd_be6b_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_7/sim/bd_be6b_second_dlmb_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_8/sim/bd_be6b_second_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_9/sim/bd_be6b_second_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work iomodule_v3_1_13 $vhdlan_opts \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/e11b/hdl/iomodule_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/ip/ip_10/sim/bd_be6b_iomodule_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/bd_0/sim/bd_be6b.v" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_0/sim/design_1_ddr4_0_2_microblaze_mcs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/phy/design_1_ddr4_0_2_phy_ddr4.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy_behav.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/ip_top/design_1_ddr4_0_2_phy.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_wtr.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ref.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_rd_wr.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_periodic.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_group.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ecc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_ctl.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_arb_p.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_arb_c.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_arb_a.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_act_timer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc_act_rank.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/controller/ddr4_v2_2_mc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ui/ddr4_v2_2_ui_wr_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ui/ddr4_v2_2_ui_rd_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ui/ddr4_v2_2_ui_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ui/ddr4_v2_2_ui.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_ar_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_aw_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_b_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_fifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_r_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_w_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_a_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_register_slice.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axi_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_axic_register_slice.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_carry_and.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_carry_latch_and.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_carry_latch_or.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_carry_or.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_command_fifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_comparator.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_comparator_sel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_comparator_sel_static.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_r_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi/ddr4_v2_2_w_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/clocking/ddr4_v2_2_infrastructure.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_write.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_wr_byte.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_wr_bit.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_sync.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_read.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_rd_en.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_pi.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_mc_odt.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_cplx_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_cplx.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_config_rom.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_addr_decode.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_top.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_cal.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/ddr4_v2_2_dp_AB9.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top/design_1_ddr4_0_2_ddr4.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top/design_1_ddr4_0_2_ddr4_mem_intfc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal/design_1_ddr4_0_2_ddr4_cal_riu.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top/design_1_ddr4_0_2.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_2/tb/design_1_ddr4_0_2_microblaze_mcs_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work jtag_axi $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/7f86/hdl/jtag_axi_v1_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_jtag_axi_0_0/sim/design_1_jtag_axi_0_0.v" \
  "../../../bd/design_1/ip/design_1_vio_0_0/sim/design_1_vio_0_0.v" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_sarn_1.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_srn_1.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_sawn_1.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_swn_1.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_sbn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_48ac_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_48ac_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_48ac_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_48ac_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_48ac_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work smartconnect_v1_0 $vhdlan_opts \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_36 $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/bc4b/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_22 $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/b16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_rst_ddr4_0_187M_0/sim/design_1_rst_ddr4_0_187M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work util_vector_logic_v2_0_5 $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../../adder.gen/sources_1/bd/design_1/ipshared/e056/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_util_vector_logic_0_0/sim/design_1_util_vector_logic_0_0.v" \
  "../../../bd/design_1/ipshared/05bc/src/ADD.v" \
  "../../../bd/design_1/ipshared/05bc/src/ADD_Element.v" \
  "../../../bd/design_1/ipshared/05bc/src/MUL.v" \
  "../../../bd/design_1/ipshared/05bc/src/MUL_Element.v" \
  "../../../bd/design_1/ipshared/05bc/src/MultiplyByQuantizedMultiplier.v" \
  "../../../bd/design_1/ipshared/05bc/src/MultiplyByQuantizedMultiplierSmallerThanOneExp.v" \
  "../../../bd/design_1/ipshared/05bc/src/SUB.v" \
  "../../../bd/design_1/ipshared/05bc/src/SUB_Element.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ipshared/05bc/src/LSU.sv" \
  "../../../bd/design_1/ipshared/05bc/src/PE_INT8_OS.sv" \
  "../../../bd/design_1/ipshared/05bc/src/SystolicArray_OS_INT8_requant_sram.sv" \
  "../../../bd/design_1/ipshared/05bc/src/banked_mem_1r1w.sv" \
  "../../../bd/design_1/ipshared/05bc/src/controller.sv" \
  "../../../bd/design_1/ipshared/05bc/src/desc_decoder.sv" \
  "../../../bd/design_1/ipshared/05bc/src/element_wise_LUT.sv" \
  "../../../bd/design_1/ipshared/05bc/src/fifo.sv" \
  "../../../bd/design_1/ipshared/05bc/src/lut_lane_mem.sv" \
  "../../../bd/design_1/ipshared/05bc/src/lut_vec_tflite.sv" \
  "../../../bd/design_1/ipshared/05bc/src/mem_bank_1r1w.sv" \
  "../../../bd/design_1/ipshared/05bc/src/mult_pipe.sv" \
  "../../../bd/design_1/ipshared/05bc/src/npu_int16.sv" \
  "../../../bd/design_1/ipshared/05bc/src/op_decoder.sv" \
  "../../../bd/design_1/ipshared/05bc/src/sram.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../bd/design_1/ipshared/05bc/src" +incdir+"../../../../../../../../../opt/Xilinx/2025.2/data/rsb/busdef" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/ip_1/rtl/map" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/ip_top" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_2/rtl/cal" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/0de9/hdl" +incdir+"../../../../adder.gen/sources_1/bd/design_1/ipshared/05bc/src" +incdir+"/opt/Xilinx/2025.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ipshared/05bc/src/npu_axi_full.v" \
  "../../../bd/design_1/ip/design_1_npu_axi_full_0_0/sim/design_1_npu_axi_full_0_0.v" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

  # delete previous design library generated data
  if [[ ($b_clean == 1) ]]; then
    clean
    echo -e "INFO: Design library generated data deleted.\n"
    exit 0
  fi

  # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_rerun == 1) ]]; then
    # keep previous state for incremental run
    return 0
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/jasper/npu/npu_testing_system/adder/adder.cache/compile_simlib/vcs"
  fi

  echo "LIBRARY_SCAN=TRUE" >> $file

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc design_1_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated design library data from the previous run
clean()
{
  files_to_remove=("${design_libs[@]}")
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="$sim_lib_dir/${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  # delete design library directory
  rm -rf $sim_lib_dir
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -rerun)         b_rerun=1         ;;
      -reset_run)     b_reset_run=1     ;;
      -clean)         b_clean=1         ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -clean is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_clean == 1) ]]; then
    echo -e "ERROR: -clean switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-rerun]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-clean]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-rerun] -- Rerun step(s) in incremental mode (data generated from the previous run will be retained).\n\
To rerun a specific step, pass the -step <name> switch in addition to -rerun switch.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-clean] -- Delete simulator generated design library data from the previous run. This switch will not\n\
execute steps defined in the script.\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_rerun=0
b_reset_run=0
b_clean=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
